// <auto-generated />
using System;
using LostPeople.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LostPeople.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LostPeopleDbContext))]
    [Migration("20260629125944_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LostPeople.Domain.Entities.Archivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreOriginal")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("PersonaId")
                        .HasColumnType("int");

                    b.Property<bool>("Publico")
                        .HasColumnType("bit");

                    b.Property<int?>("ReporteId")
                        .HasColumnType("int");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("SubidoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoContenido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.HasIndex("ReporteId");

                    b.HasIndex("SubidoPorUsuarioId");

                    b.ToTable("Archivos", (string)null);
                });

            modelBuilder.Entity("LostPeople.Domain.Entities.Auditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Detalles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entidad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("EntidadId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpOrigen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipoOperacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorNuevo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Auditorias", (string)null);
                });

            modelBuilder.Entity("LostPeople.Domain.Entities.CentroSalud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContactoEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ZonaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZonaId");

                    b.ToTable("CentrosSalud", (string)null);
                });

            modelBuilder.Entity("LostPeople.Domain.Entities.Coincidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlgoritmoUsado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaDeteccion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRevision")
                        .HasColumnType("datetime2");

                    b.Property<string>("NotasRevision")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("RegistroIngeridoId")
                        .HasColumnType("int");

                    b.Property<int>("ReportePersonaId")
                        .HasColumnType("int");

                    b.Property<string>("ResultadoRevision")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("Revisada")
                        .HasColumnType("bit");

                    b.Property<int?>("RevisorUsuarioId")
                        .HasColumnType("int");

                    b.Property<decimal>("ScoreDescripcion")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ScoreEdad")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ScoreGeneral")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ScoreNombre")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ScoreSexo")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ScoreUbicacion")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("RegistroIngeridoId");

                    b.HasIndex("ReportePersonaId");

                    b.HasIndex("Revisada")
                        .HasFilter("[Revisada] = 0");

                    b.HasIndex("RevisorUsuarioId");

                    b.HasIndex("ScoreGeneral");

                    b.HasIndex("Revisada", "ScoreGeneral")
                        .HasFilter("[Revisada] = 0");

                    b.ToTable("Coincidencias", (string)null);
                });

            modelBuilder.Entity("LostPeople.Domain.Entities.EstadoCaso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ColorHex")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OrdenFlujo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("EstadosCaso", (string)null);
                });

            modelBuilder.Entity("LostPeople.Domain.Entities.FuenteDatos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ConfiguracionJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoSalud")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FallosConsecutivos")
                        .HasColumnType("int");

                    b.Property<string>("FormatoDatos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IntervaloMinutos")
                        .HasColumnType("int");

                    b.Property<string>("MetodoAcceso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NotasLegales")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("RiesgoLegal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectorHtml")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("TotalEjecuciones")
                        .HasColumnType("int");

                    b.Property<int>("TotalRegistrosObtenidos")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimaEjecucionOk")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UltimoError")
                        .HasColumnType("datetime2");

                    b.Property<string>("UrlBase")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("FuentesDatos", (string)null);
                });

            modelBuilder.Entity("LostPeople.Domain.Entities.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CanalEnvio")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Enviada")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaLectura")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Leida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("ReportePersonaId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Titulo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReportePersonaId");

                    b.HasIndex("UsuarioId", "Leida", "FechaCreacion");

                    b.ToTable("Notificaciones", (string)null);
                });

            modelBuilder.Entity("LostPeople.Domain.Entities.PersonaReportada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CodigoSeguimiento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ColorCabello")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ColorOjos")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ColorPiel")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CondicionMedica")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("DatosSinteticos")
                        .HasColumnType("bit");

                    b.Property<string>("DescripcionFisica")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("EdadAproximada")
                        .HasColumnType("int");

                    b.Property<bool>("EsAdultoMayor")
                        .HasColumnType("bit");

                    b.Property<bool>("EsDiscapacitado")
                        .HasColumnType("bit");

                    b.Property<bool>("EsMenorEdad")
                        .HasColumnType("bit");

                    b.Property<bool>("EsViolenciaGenero")
                        .HasColumnType("bit");

                    b.Property<int>("EstadoCasoId")
                        .HasColumnType("int");

                    b.Property<decimal?>("EstaturaCm")
                        .HasPrecision(5, 1)
                        .HasColumnType("decimal(5,1)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaDesaparicion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotoOriginalUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoWebUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicamentosRequeridos")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nacionalidad")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal?>("PesoKg")
                        .HasPrecision(5, 1)
                        .HasColumnType("decimal(5,1)");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SegundoApellido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SegundoNombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SenasParticulares")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Sexo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoAlerta")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoDocumento")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal?>("UltimaUbicacionLat")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal?>("UltimaUbicacionLng")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("UltimaUbicacionTexto")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("UltimaUbicacionZonaId")
                        .HasColumnType("int");

                    b.Property<string>("Vestimenta")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoSeguimiento")
                        .IsUnique();

                    b.HasIndex("DatosSinteticos")
                        .HasFilter("[DatosSinteticos] = 0");

                    b.HasIndex("EstadoCasoId");

                    b.HasIndex("FechaDesaparicion");

                    b.HasIndex("UltimaUbicacionZonaId");

                    b.HasIndex("PrimerNombre", "SegundoNombre", "PrimerApellido", "SegundoApellido");

                    b.ToTable("PersonasReportadas", (string)null);
                });

            modelBuilder.Entity("LostPeople.Domain.Entities.RegistroIngerido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CoincidenciaProcesada")
                        .HasColumnType("bit");

                    b.Property<string>("DescripcionFisica")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("EdadAproximada")
                        .HasColumnType("int");

                    b.Property<string>("EstadoPaciente")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaIngesta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRegistroFuente")
                        .HasColumnType("datetime2");

                    b.Property<int>("FuenteId")
                        .HasColumnType("int");

                    b.Property<string>("HashContenido")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("HtmlCrudo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentificadorExterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstitucionOrigen")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Latitud")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal?>("Longitud")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("PrimerApellido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PrimerNombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ScoreMaximoCoincidencia")
                        .HasColumnType("int");

                    b.Property<string>("SegundoApellido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SegundoNombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sexo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TelefonoContacto")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UbicacionTexto")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UrlOrigen")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CoincidenciaProcesada")
                        .HasFilter("[CoincidenciaProcesada] = 0");

                    b.HasIndex("HashContenido")
                        .IsUnique()
                        .HasFilter("[HashContenido] IS NOT NULL");

                    b.HasIndex("FuenteId", "FechaRegistroFuente");

                    b.HasIndex("PrimerNombre", "PrimerApellido");

                    b.ToTable("RegistrosIngeridos", (string)null);
                });

            modelBuilder.Entity("LostPeople.Domain.Entities.Reporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoVerificacion")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DetalleLocalizacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailContacto")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("EsReporteLocalizacion")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("FuenteReporte")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IpOrigen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notas")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<string>("RelacionConDesaparecido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ReportanteUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("TelefonoContacto")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Verificado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.HasIndex("ReportanteUsuarioId");

                    b.ToTable("Reportes", (string)null);
                });

            modelBuilder.Entity("LostPeople.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Permisos")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("LostPeople.Domain.Entities.SesionUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpOrigen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("SesionesUsuario", (string)null);
                });

            modelBuilder.Entity("LostPeople.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AceptoConfidencialidad")
                        .HasColumnType("bit");

                    b.Property<bool>("AceptoTerminos")
                        .HasColumnType("bit");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Cargo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Cedula")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimoAcceso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Institucion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TokenVerificacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Verificado")
                        .HasColumnType("bit");

                    b.Property<int?>("ZonaAsignadaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.HasIndex("ZonaAsignadaId");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("LostPeople.Domain.Entities.Verificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoincidenciaId")
                        .HasColumnType("int");

                    b.Property<string>("DetalleContacto")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaVerificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetodoContacto")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notas")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Resultado")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TipoVerificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("VerificadorUsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CoincidenciaId");

                    b.HasIndex("VerificadorUsuarioId");

                    b.ToTable("Verificaciones", (string)null);
                });

            modelBuilder.Entity("LostPeople.Domain.Entities.ZonaGeografica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("LatitudCentroide")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal?>("LongitudCentroide")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ZonaPadreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Tipo");

                    b.HasIndex("ZonaPadreId");

                    b.ToTable("ZonasGeograficas", (string)null);
                });

            modelBuilder.Entity("LostPeople.Domain.Entities.Archivo", b =>
                {
                    b.HasOne("LostPeople.Domain.Entities.PersonaReportada", "Persona")
                        .WithMany("Archivos")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LostPeople.Domain.Entities.Reporte", "Reporte")
                        .WithMany("Archivos")
                        .HasForeignKey("ReporteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LostPeople.Domain.Entities.Usuario", "SubidoPorUsuario")
                        .WithMany("ArchivosSubidos")
                        .HasForeignKey("SubidoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");

                    b.Navigation("Reporte");

                    b.Navigation("SubidoPorUsuario");
                });

            modelBuilder.Entity("LostPeople.Domain.Entities.Auditoria", b =>
                {
                    b.HasOne("LostPeople.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LostPeople.Domain.Entities.CentroSalud", b =>
                {
                    b.HasOne("LostPeople.Domain.Entities.ZonaGeografica", "Zona")
                        .WithMany("CentrosSalud")
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("LostPeople.Domain.Entities.Coincidencia", b =>
                {
                    b.HasOne("LostPeople.Domain.Entities.RegistroIngerido", "RegistroIngerido")
                        .WithMany("Coincidencias")
                        .HasForeignKey("RegistroIngeridoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LostPeople.Domain.Entities.PersonaReportada", "PersonaReportada")
                        .WithMany("Coincidencias")
                        .HasForeignKey("ReportePersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LostPeople.Domain.Entities.Usuario", "Revisor")
                        .WithMany()
                        .HasForeignKey("RevisorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PersonaReportada");

                    b.Navigation("RegistroIngerido");

                    b.Navigation("Revisor");
                });

            modelBuilder.Entity("LostPeople.Domain.Entities.Notificacion", b =>
                {
                    b.HasOne("LostPeople.Domain.Entities.PersonaReportada", "PersonaReportada")
                        .WithMany("Notificaciones")
                        .HasForeignKey("ReportePersonaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LostPeople.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Notificaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PersonaReportada");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LostPeople.Domain.Entities.PersonaReportada", b =>
                {
                    b.HasOne("LostPeople.Domain.Entities.EstadoCaso", "EstadoCaso")
                        .WithMany("Personas")
                        .HasForeignKey("EstadoCasoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LostPeople.Domain.Entities.ZonaGeografica", "UltimaUbicacionZona")
                        .WithMany("PersonasReportadas")
                        .HasForeignKey("UltimaUbicacionZonaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EstadoCaso");

                    b.Navigation("UltimaUbicacionZona");
                });

            modelBuilder.Entity("LostPeople.Domain.Entities.RegistroIngerido", b =>
                {
                    b.HasOne("LostPeople.Domain.Entities.FuenteDatos", "Fuente")
                        .WithMany("RegistrosIngeridos")
                        .HasForeignKey("FuenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fuente");
                });

            modelBuilder.Entity("LostPeople.Domain.Entities.Reporte", b =>
                {
                    b.HasOne("LostPeople.Domain.Entities.PersonaReportada", "Persona")
                        .WithMany("Reportes")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LostPeople.Domain.Entities.Usuario", "Reportante")
                        .WithMany("Reportes")
                        .HasForeignKey("ReportanteUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");

                    b.Navigation("Reportante");
                });

            modelBuilder.Entity("LostPeople.Domain.Entities.SesionUsuario", b =>
                {
                    b.HasOne("LostPeople.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Sesiones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LostPeople.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("LostPeople.Domain.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LostPeople.Domain.Entities.ZonaGeografica", "ZonaAsignada")
                        .WithMany("UsuariosAsignados")
                        .HasForeignKey("ZonaAsignadaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Rol");

                    b.Navigation("ZonaAsignada");
                });

            modelBuilder.Entity("LostPeople.Domain.Entities.Verificacion", b =>
                {
                    b.HasOne("LostPeople.Domain.Entities.Coincidencia", "Coincidencia")
                        .WithMany("Verificaciones")
                        .HasForeignKey("CoincidenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LostPeople.Domain.Entities.Usuario", "Verificador")
                        .WithMany("Verificaciones")
                        .HasForeignKey("VerificadorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coincidencia");

                    b.Navigation("Verificador");
                });

            modelBuilder.Entity("LostPeople.Domain.Entities.ZonaGeografica", b =>
                {
                    b.HasOne("LostPeople.Domain.Entities.ZonaGeografica", "ZonaPadre")
                        .WithMany("Hijos")
                        .HasForeignKey("ZonaPadreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ZonaPadre");
                });

            modelBuilder.Entity("LostPeople.Domain.Entities.Coincidencia", b =>
                {
                    b.Navigation("Verificaciones");
                });

            modelBuilder.Entity("LostPeople.Domain.Entities.EstadoCaso", b =>
                {
                    b.Navigation("Personas");
                });

            modelBuilder.Entity("LostPeople.Domain.Entities.FuenteDatos", b =>
                {
                    b.Navigation("RegistrosIngeridos");
                });

            modelBuilder.Entity("LostPeople.Domain.Entities.PersonaReportada", b =>
                {
                    b.Navigation("Archivos");

                    b.Navigation("Coincidencias");

                    b.Navigation("Notificaciones");

                    b.Navigation("Reportes");
                });

            modelBuilder.Entity("LostPeople.Domain.Entities.RegistroIngerido", b =>
                {
                    b.Navigation("Coincidencias");
                });

            modelBuilder.Entity("LostPeople.Domain.Entities.Reporte", b =>
                {
                    b.Navigation("Archivos");
                });

            modelBuilder.Entity("LostPeople.Domain.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("LostPeople.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("ArchivosSubidos");

                    b.Navigation("Notificaciones");

                    b.Navigation("Reportes");

                    b.Navigation("Sesiones");

                    b.Navigation("Verificaciones");
                });

            modelBuilder.Entity("LostPeople.Domain.Entities.ZonaGeografica", b =>
                {
                    b.Navigation("CentrosSalud");

                    b.Navigation("Hijos");

                    b.Navigation("PersonasReportadas");

                    b.Navigation("UsuariosAsignados");
                });
#pragma warning restore 612, 618
        }
    }
}
